sudo: required
services:
 - docker

before_install:
 - docker build -t yograj/react-test -f ./client/Dockerfile.dev ./client

script:
 - echo "Hi"

after_success:
 - docker build -t yograj/multi-client ./client
 - docker build -t yograj/multi-nginx ./nginx
 - docker build -t yograj/multi-server ./server
 - docker build -t yograj/multi-worker ./worker

 - echo "$dockerpass" | docker login -u "$dockerid" --password-stdin

 - docker push yograj/multi-client
 - docker push yograj/multi-nginx
 - docker push yograj/multi-server
 - docker push yograj/multi-worker

deploy:
 provider: elasticbeanstalk
 region: "us-east-1"
 app: multi-docker 
 env: MultiDocker-env 
 bucket_name: elasticbeanstalk-us-east-1-949813704436
 bucket_path: "multi-docker"
 on:
  branch: master
 access_key_id: $aws_access_key
 secret_access_key:
  secure: "$aws_secret_key"
